[project]
name = "Farm Tracker"
version = "1.0.0"
authors = [{ name = "Pyrex" }]
description = "Track some farms"

[tool.sdkmod]
name = "Farm Tracker"
license = {name = "GPL3", url = "https://choosealicense.com/licenses/gpl-3.0/" }
version = "1.0.0"