maplist: list = [
    "arid_p",
    "Arid_SkagGully_P",
    "Dry_P",
    "Arid_Bunker_P",
    "Arid_Mine_P",
    "interlude_1_p",
    "Arid_Cave_P",
    "scrap_newhaven_p",
    "Scrap_TrashCave_P",
    "scrap_p",
    "scrap_scrapyard_p",
    "Scrap_PirateBay_P",
    "Scrap_Canyon_P",
    "Trash_p",
    "scrap_trashcoast_p",
    "Scrap_OldHaven_P",
    "Interlude_2_P",
    "Interlude_2_Cave_P",
    "Waste_CrimsonBunker_P",
    "Waste_Crimson_P",
    "Waste_Descent_P",
    "Waste_Digsite_P",
    "Waste_Vault_P",
    "Arid_Arena_Coliseum_P",
    "Waste_Arena_Ruins_P",
    "Scrap_Arena_Sewer_P",
    "dlc1_swamp_ned_p",
    "dlc1_island_p",
    "dlc1_zombieHaven_P",
    "dlc1_mill_p",
    "dlc1_mill_boss_p",
    "dlc1_monsterhouse_p",
    "dlc2_lobby_p",
    "dlc2_hellburb_p",
    "dlc2_Gully_P",
    "dlc2_ruins_p",
    "dlc3_HUB_p",
    "dlc3_NLanceStrip_p",
    "dlc3_prison_p",
    "dlc3_lakebed_p",
    "dlc3_southlake_p",
    "dlc3_SLanceStrip_p",
    "dlc3_lancedepot_p",
    "dlc3_uberboss_p",
    "dlc3_moxxieplace_p",
    "dlc3_circle_p",
    "dlc3_gondola_p",
    "DLC4_Tartarus_Station_p",
    "DLC4_Sanders_Gorge_p",
    "DLC4_Hyperion_Dump_p",
    "DLC4_Dividing_Faults_p",
    "DLC4_SS_Canyon_p",
    "DLC4_Arid_Badlands_p",
    "DLC4_Wayward_Pass_p",
    "Scrap_Oasis_P",
]

mapnamelist: list = [
    "Arid Badlands",
    "Skag Gully",
    "Arid Hills",
    "Sledge's Safe House",
    "Headstone Mine",
    "Dahl Headland",
    "Lost Cave",
    "New Haven",
    "Tetanus Warren",
    "Rust Commons West",
    "Earl's Scrapyard",
    "Treacher's Landing",
    "Krom's Canyon",
    "Rust Commons East",
    "Trash Coast",
    "Old Haven",
    "Salt Flats",
    "Back Door",
    "Crimson Fastness",
    "Crimson Enclave",
    "Descent",
    "Eridian Promontory",
    "The Vault",
    "Fyrestone Coliseum",
    "Ruins Arena",
    "The Cesspool",
    "Hallow's End",
    "Jakobs Cove",
    "Dead Haven",
    "The Lumber Yard",
    "The Mill",
    "Generally Hospital",
    "The Underdome",
    "hell-BURBIA",
    "The Gully",
    "Angelic Ruins",
    "T-Bone Junction",
    "The Ridgeway",
    "Lockdown Palace",
    "Sunken Sea",
    "Deep Fathoms",
    "The Crimson Tollway",
    "Crimson Armory",
    "Crawmerax's Lair",
    "Moxxi's Red Light",
    "Circle of Duty",
    "Road's End",
    "Tartarus Station",
    "Sanders Gorge",
    "Hyperion Dump",
    "Dividing Faults",
    "Scorched Snake Canyon",
    "Arid Badlands (DLC4)",
    "Wayward Pass",
    "Oasis",
]